name: Run unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: read
  issues: write
  checks: write

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
      - name: Use Node JS LTS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:prod
      - name: Report test results (LRU)
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/test-results-lru.xml'
          check_name: 'LRU Cache Test Report'
